on:
  - push
  - pull_request

env:
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/_vcpkg_cache

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: curl -L https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/master-796e77c/clang-format-20_linux-amd64 -o /tmp/clang-format
      - run: chmod +x /tmp/clang-format
      - run: /tmp/clang-format -i *.c *.h
      - run: git diff --exit-code
  build:
    strategy:
      matrix:
        os: [linux, mac, windows]
        include:
        - os: linux
          image: ubuntu-latest
        - os: mac
          image: macos-latest
        - os: windows
          image: windows-latest
          cmake_args: -A x64
      fail-fast: false
    runs-on: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v5
      - run: mkdir _vcpkg_cache
      - uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.cmake', 'vcpkg.json') }}
          restore-keys: ${{ runner.os }}-vcpkg-
      - run: cmake -S . -B _build -DCMAKE_BUILD_TYPE=Release -DENABLE_JPEG=ON -DENABLE_PNG=ON -DENABLE_TIFF=ON -DENABLE_EXR=ON ${{ matrix.cmake_args }}
      - run: cmake --build _build --config Release
